compoje:
  docker:
    stack: redis-example
  providers: []
    # - name: my-vault
    #   type: compoje.providers.vault/vault
    #   addr: "http://localhost:8200"
  secrets: []
    # - name: cert-key
    #   provider: my-vault
    #   local-path: "nginx/cert.key"
    #   spit-key: cert.key
    #   mount-path: "secret"
    #   secret-path: nginx
    # - name: cert
    #   provider: my-vault
    #   local-path: "nginx/cert.key"
    #   spit-key: cert.crt
    #   mount-path: "secret"
    #   secret-path: nginx
  values:
    resource-reservations-mem: 128m

version: '3.9'
services:
  nginx:
    image: docker.io/nginx:stable
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 0
        order: start-first
      resources:
        limits:
          memory: 4g
          cpus: "4"
        reservations:
          memory: <{ values.resource-reservations-mem }>
    networks:
      - host_network
    configs:
      - source: nginx_cfg
        target: /etc/nginx/conf.d/default.conf

networks:
  host_network:
    name: host
    external: true

configs:
  nginx_cfg:
    file: config/nginx.conf
    name: nginx_cfg-<% file-hash 'config/nginx.conf' %>
