version: '3.9'

services:
  nginx:
    image: docker.io/nginx:stable
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 0
        order: start-first
      resources:
        limits:
          memory: 4g
          cpus: "4"
        reservations:
          memory: 128m
    networks:
      - host_network
    configs:
      - source: nginx_cfg
        target: /etc/nginx/conf.d/default.conf


networks:
  host_network:
    name: host
    external: true

configs:
  nginx_cfg:
    file: config/nginx.conf
    name: nginx_cfg-465b07
